### ISSUE TITLE
Can this run in browser?

### ISSUE THREAD

**Issue by hillac** [hyzyla/pdfium#14]
I can't seem to get it running in a browser, should I be able to? There's an error with the import and I'm not sure it it's vite's fault.

**Comment by hyzyla** [comment]
Hello! I've never tried to run it in browser, so it might not work there. Probably I can replace all node API with universal one and bump major version

**Comment by hyzyla** [comment]
I failed to configure the build for the browser. I've removed the dependency on Buffer and used Uint8Array everywhere. However, the hardest part is figuring out how to bundle the WASM binary and provide a universal package for both Node.js and the browser. If you have any ideas or would like to contribute, I would be grateful, because currently I don't know how to do it properly. 

Ideally, the end user should have the option to use an inlined WASM module, provide a URL, or supply the WASM binary. Additionally, it should work in both Node.js (CommonJS and ES module) and the browser.

Here is basic idea that I was trying to implement:
```typescript
export class PDFiumLibrary {
  private readonly module: t.PDFium;
  static async init(options: {
    wasmBinary?: ArrayBuffer;
    wasmUrl?: string;
  }) {

    const moduleOptions: any = {};
    if (options.wasmBinary) {
      options.wasmBinary = options.wasmBinary;
    } else if (options.wasmUrl) {
      options.locateFile = (path: string) => options.wasmUrl;
    } else {
      if (typeof window !== "undefined") {
        const { wasmInlined } = await import("./pdfium.base64");
        options.wasmBinary = wasmInlined;
      } else {
        // for node.js just do nothing, should be handled by emscripten wrappers
      }
    }

    const module = await vendor(options);
}
```

Here is a great article that can be a good starting point.  https://nickb.dev/blog/recommendations-when-publishing-a-wasm-library/

**Comment by hyzyla** [comment]
Someone pointed me out to use CDN for the first setup to download .wasm binary. So I going to try this method this week

**Comment by hyzyla** [comment]
Thanks! In even don't know that https://cdn.jsdelivr.net host all npm packages automatically. I'll try to integrate it later with my repo

**Comment by hyzyla** [comment]
@hillac  check this out  https://github.com/hyzyla/pdfium/releases/tag/v2.0.0 I also prepeared small demo https://pdfium.js.org/demo

**Comment by hyzyla** [comment]
Yeah, I also don't like that solution much either, but it was a compromise between shipping the WASM binary in base64 within the code or asking the user to configure a loader in their bundle to provide a URL to the asset. I checked, and several popular packages handle it this way, so it should work for quick bootstrap. They warn you in the documentation or browser console that it might have some issues (I also warn about it)

One option that might better solve this issue is to use `import.meta.url` to point to the WASM binary in the module. However, I haven't tried it yet, so I'm not sure how well it works with modern bundlers or whether they can resolve such links in my packages to a relative path properly.

If you have any other ideas on how to resolve this issue, please let me know. I'm open for suggestions on this.
